server:
  port: 8080

app:
  data-dir: ${APP_DATA_DIR:./data}
  auth:
    secret: ${FACTURATION_AUTH_SECRET:dev-secret-change-me}
  uploads-dir: ${app.data-dir}/uploads

spring:
  datasource:
    url: jdbc:sqlite:${app.data-dir}/app-spring.sqlite3
    driver-class-name: org.sqlite.JDBC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
