server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:../data/app-spring.sqlite3
    driver-class-name: org.sqlite.JDBC
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

app:
  auth:
    secret: ${FACTURATION_AUTH_SECRET:dev-secret-change-me}
  uploads-dir: ../data/uploads

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
